In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import average_precision_score
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import hamming_loss
import warnings
warnings.filterwarnings(action='ignore')

# 메뉴

In [2]:
df = pd.read_excel('../data/input_data.xlsx')
df.head()

메뉴  빵  치즈               소스  랜치  마요네즈  스위트 어니언  허니 머스타드  스위트 칠리  핫 칠리  ...  \
0   8  3   1       ['4', '5']   0     0        0        1       1     0  ...   
1  11  3   2      ['5', '14']   0     0        0        0       1     0  ...   
2  18  3   2      ['5', '14']   0     0        0        0       1     0  ...   
3   8  5   2       ['3', '5']   0     0        1        0       1     0  ...   
4   5  5   1  ['1', '3', '5']   1     0        1        0       1     0  ...   

   367       368  369       370  371  372       373       374       375  \
0  0.0  0.000000  0.0  0.000000  0.0  0.0  0.000000  0.000000  0.000000   
1  0.0  0.086614  0.0  0.000000  0.0  0.0  0.099747  0.077295  0.000000   
2  0.0  0.000000  0.0  0.000000  0.0  0.0  0.000000  0.000000  0.000000   
3  0.0  0.000000  0.0  0.000000  0.0  0.0  0.000000  0.000000  0.000000   
4  0.0  0.000000  0.0  0.142475  0.0  0.0  0.000000  0.000000  0.142475   

        376  
0  0.000000  
1  0.000000  
2  0.000000  
3  0.000000  
4  0.142475  

[5 rows x 396 columns]

In [3]:
X1 = df[["메뉴"]].to_numpy()
y1 = np.asarray(df[df.columns[4:19]])

In [4]:
X1, X1.shape

(array([[ 8],
        [11],
        [18],
        ...,
        [18],
        [18],
        [18]], dtype=int64),
 (1678, 1))

In [5]:
y1, y1.shape

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 1, 0],
        [0, 0, 0, ..., 0, 1, 0],
        ...,
        [0, 0, 0, ..., 0, 1, 0],
        [0, 0, 0, ..., 0, 1, 0],
        [0, 0, 0, ..., 0, 1, 0]], dtype=int64),
 (1678, 15))

In [6]:
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, random_state=42)

In [7]:
clf1 = MLPClassifier(activation='logistic', random_state=42).fit(X1_train, y1_train)

In [8]:
clf1.predict(X1_test[:5])

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [9]:
y1_test[:5]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0],
       [1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [10]:
y1_pred = clf1.predict(X1_test)
hamming_loss(y1_test, y1_pred)

0.15301587301587302

In [11]:
ap_sum = 0
for i in range(y1_test.shape[0]):
    ap_sum += average_precision_score(y1_test[i], y1_pred[i])
mAP = ap_sum/y1_test.shape[0]
print(mAP)

0.1660317460317468


# 메뉴 + 빵, 치즈

In [12]:
df.head()

메뉴  빵  치즈               소스  랜치  마요네즈  스위트 어니언  허니 머스타드  스위트 칠리  핫 칠리  ...  \
0   8  3   1       ['4', '5']   0     0        0        1       1     0  ...   
1  11  3   2      ['5', '14']   0     0        0        0       1     0  ...   
2  18  3   2      ['5', '14']   0     0        0        0       1     0  ...   
3   8  5   2       ['3', '5']   0     0        1        0       1     0  ...   
4   5  5   1  ['1', '3', '5']   1     0        1        0       1     0  ...   

   367       368  369       370  371  372       373       374       375  \
0  0.0  0.000000  0.0  0.000000  0.0  0.0  0.000000  0.000000  0.000000   
1  0.0  0.086614  0.0  0.000000  0.0  0.0  0.099747  0.077295  0.000000   
2  0.0  0.000000  0.0  0.000000  0.0  0.0  0.000000  0.000000  0.000000   
3  0.0  0.000000  0.0  0.000000  0.0  0.0  0.000000  0.000000  0.000000   
4  0.0  0.000000  0.0  0.142475  0.0  0.0  0.000000  0.000000  0.142475   

        376  
0  0.000000  
1  0.000000  
2  0.000000  
3  0.000000  
4  0.142475  

[5 rows x 396 columns]

In [13]:
X2 = df[["메뉴", "빵", "치즈"]].to_numpy()
y2 = np.asarray(df[df.columns[4:19]])

In [14]:
X2, X2.shape

(array([[ 8,  3,  1],
        [11,  3,  2],
        [18,  3,  2],
        ...,
        [18,  4,  4],
        [18,  5,  4],
        [18,  6,  4]], dtype=int64),
 (1678, 3))

In [15]:
y2, y2.shape

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 1, 0],
        [0, 0, 0, ..., 0, 1, 0],
        ...,
        [0, 0, 0, ..., 0, 1, 0],
        [0, 0, 0, ..., 0, 1, 0],
        [0, 0, 0, ..., 0, 1, 0]], dtype=int64),
 (1678, 15))

In [16]:
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, random_state=42)

In [17]:
clf2 = MLPClassifier(activation='logistic', random_state=42).fit(X2_train, y2_train)

In [18]:
clf2.predict(X2_test[:5])

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [19]:
y2_test[:5]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0],
       [1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [20]:
y2_pred = clf2.predict(X2_test)
hamming_loss(y2_test, y2_pred)

0.15317460317460319

In [21]:
ap_sum = 0
for i in range(y2_test.shape[0]):
    ap_sum += average_precision_score(y2_test[i], y2_pred[i])
mAP = ap_sum/y2_test.shape[0]
print(mAP)

0.1637301587301594


# 메뉴 + 빵, 치즈 + 설명

In [22]:
df.head()

메뉴  빵  치즈               소스  랜치  마요네즈  스위트 어니언  허니 머스타드  스위트 칠리  핫 칠리  ...  \
0   8  3   1       ['4', '5']   0     0        0        1       1     0  ...   
1  11  3   2      ['5', '14']   0     0        0        0       1     0  ...   
2  18  3   2      ['5', '14']   0     0        0        0       1     0  ...   
3   8  5   2       ['3', '5']   0     0        1        0       1     0  ...   
4   5  5   1  ['1', '3', '5']   1     0        1        0       1     0  ...   

   367       368  369       370  371  372       373       374       375  \
0  0.0  0.000000  0.0  0.000000  0.0  0.0  0.000000  0.000000  0.000000   
1  0.0  0.086614  0.0  0.000000  0.0  0.0  0.099747  0.077295  0.000000   
2  0.0  0.000000  0.0  0.000000  0.0  0.0  0.000000  0.000000  0.000000   
3  0.0  0.000000  0.0  0.000000  0.0  0.0  0.000000  0.000000  0.000000   
4  0.0  0.000000  0.0  0.142475  0.0  0.0  0.000000  0.000000  0.142475   

        376  
0  0.000000  
1  0.000000  
2  0.000000  
3  0.000000  
4  0.142475  

[5 rows x 396 columns]

In [23]:
X3 = df.drop(columns=['소스','랜치', '마요네즈', '스위트 어니언', '허니 머스타드', '스위트 칠리', '핫 칠리', '사우스웨스트 치폴레',
                         '머스타드', '홀스래디쉬', '올리브 오일', '레드와인식초', '소금', '후추', '스모크 바비큐', '이탈리안 드레싱'])
X3 = X3.to_numpy()
X3, X3.shape

(array([[ 8.        ,  3.        ,  1.        , ...,  0.        ,
          0.        ,  0.        ],
        [11.        ,  3.        ,  2.        , ...,  0.07729536,
          0.        ,  0.        ],
        [18.        ,  3.        ,  2.        , ...,  0.        ,
          0.        ,  0.        ],
        ...,
        [18.        ,  4.        ,  4.        , ...,  0.        ,
          0.        ,  0.        ],
        [18.        ,  5.        ,  4.        , ...,  0.        ,
          0.        ,  0.        ],
        [18.        ,  6.        ,  4.        , ...,  0.        ,
          0.        ,  0.        ]]),
 (1678, 380))

In [24]:
y3 = np.asarray(df[df.columns[4:19]])
y3, y3.shape

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 1, 0],
        [0, 0, 0, ..., 0, 1, 0],
        ...,
        [0, 0, 0, ..., 0, 1, 0],
        [0, 0, 0, ..., 0, 1, 0],
        [0, 0, 0, ..., 0, 1, 0]], dtype=int64),
 (1678, 15))

In [25]:
X3_train, X3_test, y3_train, y3_test = train_test_split(X3, y3, random_state=42)

In [26]:
clf3 = MLPClassifier(activation='logistic', random_state=42).fit(X3_train, y3_train)

In [27]:
clf3.predict(X3_test[:5])

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [28]:
y3_test[:5]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0],
       [1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [29]:
y3_pred = clf3.predict_proba(X3_test)
hamming_loss(y3_test, clf3.predict(X3_test))

0.13873015873015873

In [30]:
ap_sum = 0
for i in range(y3_test.shape[0]):
    ap_sum += average_precision_score(y3_test[i], y3_pred[i])
mAP = ap_sum/y3_test.shape[0]
print(mAP)

0.6438791477481947
